In [13]:
import pandas as pd
from pathlib import Path

current_dir = Path().resolve()
dataset_path = current_dir.parent.parent / "src" / "dataset_creator" / "data" / "output" / "dataset.csv"

df = pd.read_csv(dataset_path)
display(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Air Pollutant                25723 non-null  object
 1   Air Pollutant Description    25723 non-null  object
 2   Data Aggregation Process     25723 non-null  object
 3   Year                         25723 non-null  object
 4   Air Pollution Level          25723 non-null  float64
 5   Unit Of Air Pollution Level  25723 non-null  object
 6   Air Quality Station Type     25723 non-null  object
 7   Air Quality Station Area     25723 non-null  object
 8   Longitude                    25723 non-null  float64
 9   Latitude                     25723 non-null  float64
 10  Altitude                     25723 non-null  float64
 11  Province                     25723 non-null  object
 12  Quality                      25723 non-null  object
 13  Respiratory_diseases_total   25723 non-null  float64
 14  Life_expectancy_total        25723 non-null  float64
 15  pib                          25723 non-null  float64
dtypes: float64(7), object(9)
memory usage: 3.1+ MB

None

,Air Pollutant,Air Pollutant Description,Data Aggregation Process,Year,Air Pollution Level,Unit Of Air Pollution Level,Air Quality Station Type,Air Quality Station Area,Longitude,Latitude,Altitude,Province,Quality,Respiratory_diseases_total,Life_expectancy_total,pib
0,no2,Nitrogen dioxide (air),Annual mean / 1 calendar year,2000-01-01,37.381,ug/m3,Traffic,urban,-3.6839,41.6711,865.0,Burgos,BUENA,403.000,80.47,17.824
1,no2,Nitrogen dioxide (air),Annual mean / 1 calendar year,2000-01-01,12.899,ug/m3,Industrial,suburban,-0.9133,37.6033,60.0,Murcia,BUENA,1.077,78.42,13.679
2,no2,Nitrogen dioxide (air),Annual mean / 1 calendar year,2000-01-01,35.341,ug/m3,Traffic,urban,1.2422,41.1225,23.0,Tarragona,BUENA,630.000,79.20,20.226
3,no2,Nitrogen dioxide (air),Annual mean / 1 calendar year,2000-01-01,15.752,ug/m3,Background,urban,-1.8521,38.9793,686.0,Albacete,BUENA,355.000,79.94,12.032
4,no2,Nitrogen dioxide (air),Annual mean / 1 calendar year,2000-01-01,17.067,ug/m3,Background,suburban,-4.0197,39.8689,500.0,Toledo,BUENA,568.000,80.22,13.063

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25726 entries, 0 to 25725
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Air Pollutant                25726 non-null  object
 1   Air Pollutant Description    25726 non-null  object
 2   Data Aggregation Process     25726 non-null  object
 3   Year                         25726 non-null  object
 4   Air Pollution Level          25726 non-null  float64
 5   Unit Of Air Pollution Level  25726 non-null  object
 6   Air Quality Station Type     25726 non-null  object
 7   Air Quality Station Area     25726 non-null  object
 8   Longitude                    25726 non-null  float64
 9   Latitude                     25726 non-null  float64
 10  Altitude                     25723 non-null  float64
 11  Province                     25726 non-null  object
 12  Quality                      25726 non-null  object
 13  Respiratory_diseases_total   25726 non-null  float64
 14  Life_expectancy_total        25726 non-null  float64
 15  pib                          25726 non-null  float64
dtypes: float64(7), object(9)
memory usage: 3.1+ MB

In [11]:
df.dropna(inplace=True)
df.info()
df.to_csv(dataset_path, index=False)

<class 'pandas.core.frame.DataFrame'>
Index: 25723 entries, 0 to 25725
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Air Pollutant                25723 non-null  object
 1   Air Pollutant Description    25723 non-null  object
 2   Data Aggregation Process     25723 non-null  object
 3   Year                         25723 non-null  object
 4   Air Pollution Level          25723 non-null  float64
 5   Unit Of Air Pollution Level  25723 non-null  object
 6   Air Quality Station Type     25723 non-null  object
 7   Air Quality Station Area     25723 non-null  object
 8   Longitude                    25723 non-null  float64
 9   Latitude                     25723 non-null  float64
 10  Altitude                     25723 non-null  float64
 11  Province                     25723 non-null  object
 12  Quality                      25723 non-null  object
 13  Respiratory_diseases_total   25723 non-null  float64
 14  Life_expectancy_total        25723 non-null  float64
 15  pib                          25723 non-null  float64
dtypes: float64(7), object(9)
memory usage: 3.3+ MB

# O2

In [7]:
o2_df = df[df["Air Pollutant"] == "o2"].copy()
df.describe()

,Air Pollution Level,Longitude,Latitude,Altitude,Respiratory_diseases_total,Life_expectancy_total,pib
count,25726.000000,25726.000000,25726.000000,25723.000000,25726.000000,25726.000000,25726.000000
mean,20.881927,-3.122618,40.760631,344.797885,321.373308,82.107590,23.400231
std,18.256379,3.001354,2.176037,336.994141,332.107194,1.405933,5.385038
min,0.016000,-9.186100,36.135000,1.000000,1.000000,77.320000,10.432000
25%,6.904250,-5.638900,39.472800,40.000000,2.470000,81.170000,19.280000
50%,15.470000,-3.579750,41.238900,216.000000,234.000000,82.260000,22.405000
75%,28.260000,-0.603300,42.703600,619.000000,611.000000,83.140000,27.505000
max,103.407000,3.315800,43.698300,1930.000000,999.000000,84.930000,38.711000